# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbc6d04d8623d0c113239d09a387be27b9e3f34c5a7234581c3fbecfde0dc3e23646d83909c1286c2a4e1008d4e86f6e5d35fd78f655344c8da095f57eb29e92

test:
  secret_key_base: 0c3c1e969224a96f2cb595366a6a442e96df63a5b14e910fb6e4acf78124dfa18de171a4286ebbd0fe0516eb043f922c927a0793cf680635f0b0a702473dde41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
